version: '3.8'

services:
  web:
    build: .
    ports:
      - 5004:5004
      - 8888:8888
    volumes:
      - .:/ClusterApp
    environment:
      - PYTHONPATH=/ClusterApp

  # test:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: cluster_app_test
  #   command: ["pytest"]
  #   volumes:
  #     - .:/ClusterApp
  #   environment:
  #     - FLASK_ENV=test
  #     - PYTHONPATH=/ClusterApp
  #   working_dir: /ClusterApp
  #   depends_on:
  #     - web